name: Build assets

on:
  pull_request:
  push:
    branches:
      - "**"      
    tags-ignore:
      - "**"

jobs:
  build-assets:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            nodejs-version: 18
            # Just one case may have this set to yes
            update-repo: yes
    name: Build assets (node ${{ matrix.nodejs-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs-version }}

      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NodeJS dependencies
        run: |
          cd "${{ github.workspace }}/build"
          npm ci
      - name: Build assets (dev)
        run: |
          cd "${{ github.workspace }}/build"
          npm run-script dev
      - name: Tell git to ignore the built files
        run: |
          cd "${{ github.workspace }}/build"
          npm run-script git-skip
      - name: Check that git thinks the repo is clean
        run: |
          cd "${{ github.workspace }}"
          git diff --exit-code --name-status
      - name: Revert changed files
        run: |
          cd "${{ github.workspace }}/build"
          npm run-script git-revert
      - name: Check that git thinks the repo is clean
        run: |
          cd "${{ github.workspace }}"
          git diff --exit-code --name-status
      - name: Build assets (prod)
        run: |
          cd "${{ github.workspace }}/build"
          npm run-script prod
      - name: Update repository
        if: matrix.update-repo == 'yes'
        run: |
          cd '${{ github.workspace }}'
          if git diff --exit-code --name-status; then
              echo "Repository not updated because no change has been detected"
          elif [ '${{ github.event_name }}' != 'push' ]; then
            echo "Repository not updated because it's a '${{ github.event_name }}' operation and not a 'push' one"
          elif [ '${{ github.repository }}' != 'concretecms/concretecms' ]; then
            echo "Repository not updated because it's '${{ github.repository }}' and not 'concretecms/concretecms'"
          else
            echo 'Changes detected!'
            git config --local user.name 'GitHub Action'
            git config --local user.email 'noreply@concretecms.org'
            git add -A
            git commit -m 'Update built assets'
            git push
          fi
